### PR TITLE
recoverylog/exact offsets

### LINKED ISSUE #26: recoverylog: exact offset tracking to enable deletions
As a storage owner, I want `recoverylog` hints to represent exact first/last byte offsets so that I can identify portions of a `recoverylog` which are no longer needed.

Criteria:
 * Segments of hints produced by `recoverylog.Playback` include exact begin / end offsets.

### PR DESCRIPTION
**Pull request by jgraettinger**
Fixes #26.

This series of commits extends `RecordedOp` with first and last offset "meta" fields -- fields not actually serialized by the `Recorder`, but passed to `FSM` for tracking of relevant hints.

Adding `LastOffset` in particular enables `FSMHints` to track exact start _and stop_ offsets of log `Segments`, which means that we can now use hints to determine whether a given log fragment is still necessary to the reproduction of those hints (and if not, we can delete it ala #27).

Also /cc @julianvmodesto if you're interested.

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/gazette/39)

### CODE REVIEW

**Comment by rupertchen** [comment]
Review of [r1,r4]. Resuming my review tomorrow.

---

Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: 7 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[charts/gazette/templates/deployment.yaml, line 50 at r3](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42odxrp-KaZng4oF4f:-L42odxrp-KaZng4oF4g:b-tf7f2z) ([raw file](https://github.com/liveramp/gazette/blob/80cb5e595348d57038736c90784a8b5608c3693e/charts/gazette/templates/deployment.yaml#L50)):*
> ```YAML
>           value: {{ .Values.aws.defaultRegion }}
>         - name: ETCD_SERVICE_ENDPOINT
>           value: {{ .Values.etcd }}
> ```

I agree with using the env var over the flag, but I want to confirm that this was changed as a matter of preference and not because support for the flag was removed. As far as I can tell, an `-etcd` flag still exists and expects the same `<host>:<port>` format as before.

---

*[pkg/recoverylog/recorded_op.proto, line 11 at r1](https://reviewable.io:443/reviews/liveramp/gazette/39#-L422-028BlrHTkTuGUo:-L422-028BlrHTkTuGUp:bs67rh5) ([raw file](https://github.com/liveramp/gazette/blob/42573a9d13a0eed7704e7e02c8775f71a69add64/pkg/recoverylog/recorded_op.proto#L11)):*
> ```protobuf
> option (gogoproto.sizer_all) = true;
> option (gogoproto.stringer_all) = true;
> option (gogoproto.goproto_stringer_all) = false;
> ```

Just curious: What was the reason for not using the default `String()` methods before? Is this change related to the migration to proto3?

---

*[pkg/recoverylog/recorded_op.proto, line 23 at r1](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42TlOQ_OauWR2wZnnZ:-L42TlORZYLFkhcV27wi:b-y2rtj3) ([raw file](https://github.com/liveramp/gazette/blob/2f7d5b39663ab46c6d1745d814376d01d976957b/pkg/recoverylog/recorded_op.proto#L23)):*
> ```protobuf
>   fixed32 checksum = 2;
> 
>   // Author is the unique ID of the Recorder which write this RecordedOp.
> ```

Nit: write => wrote

---

*[test/NOTES.rst, line 4 at r4](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42pl1OTtlez3kjc3q3:-L42pl1OTtlez3kjc3q4:b-s9zhz7) ([raw file](https://github.com/liveramp/gazette/blob/5f39cab876301ababbacd2352b4cf3fc4a0bc030/test/NOTES.rst#L4)):*
> ```reStructuredText
> ============================================
> 
> Bootstrap an Etcd cluster using [Etcd operator](https://coreos.com/blog/introducing-the-etcd-operator.html) ::
> ```

RST syntax: [embeded link](http://docutils.sourceforge.net/docs/user/rst/quickref.html#external-hyperlink-targets):

```rst
Bootstrap an Etcd cluster using `Etcd operator <https://coreos.com/blog/introducing-the-etcd-operator.html>`_.
```

---

*[test/NOTES.rst, line 13 at r4](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42riOOK57qrg3IuSDK:-L42riOOK57qrg3IuSDL:b-i4cbqz) ([raw file](https://github.com/liveramp/gazette/blob/5f39cab876301ababbacd2352b4cf3fc4a0bc030/test/NOTES.rst#L13)):*
> ```reStructuredText
>   helm install stable/minio --name minio -f test/minio-values.yaml
> 
> This will setup the `examples` bucket. If needed, additional buckets can be created
> ```

RST syntax: [inline literal](http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup), use double backquotes.

```rst
This will setup the ``examples`` bucket.
```

There's several instances of this in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/39#-:-L42ujnMFMhxZq9WuYks:b2y4xw4)*

**Comment by jgraettinger** [comment]
Review status: 7 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[charts/gazette/templates/deployment.yaml, line 50 at r3](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42odxrp-KaZng4oF4f:-L43vZz7CjYgwfS0fLyu:b65ws9a) ([raw file](https://github.com/liveramp/gazette/blob/80cb5e595348d57038736c90784a8b5608c3693e/charts/gazette/templates/deployment.yaml#L50)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

I agree with using the env var over the flag, but I want to confirm that this was changed as a matter of preference and not because support for the flag was removed. As far as I can tell, an `-etcd` flag still exists and expects the same `<host>:<port>` format as before.
</blockquote></details>

Hmm, this was driven by encountering a startup error on the examples. I assumed it was due to an intended removal of the flag and made this change mechanically. Though, looks like the flag changed from `etcdEndpoint` to `etcd` (we should confirm the internal project isn't affected).

---

*[pkg/recoverylog/recorded_op.proto, line 11 at r1](https://reviewable.io:443/reviews/liveramp/gazette/39#-L422-028BlrHTkTuGUo:-L43wIzlwm6Wc9VEP5hA:b-lz9q0m) ([raw file](https://github.com/liveramp/gazette/blob/42573a9d13a0eed7704e7e02c8775f71a69add64/pkg/recoverylog/recorded_op.proto#L11)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Just curious: What was the reason for not using the default `String()` methods before? Is this change related to the migration to proto3?
</blockquote></details>

Not related to migration. `stringer_all` and `goptoto_stringer_all` are duplicative IIRC and in any case, it's not clear why we need them over standard `fmt` behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/39)*

**Comment by rupertchen** [comment]
Publishing feedback of [r5,r6].

---

Reviewed 4 of 4 files at r5, 1 of 1 files at r6.
Review status: 9 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[charts/gazette/templates/deployment.yaml, line 50 at r3](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42odxrp-KaZng4oF4f:-L46KThFqm--HDpB1578:b-k0ro0n) ([raw file](https://github.com/liveramp/gazette/blob/80cb5e595348d57038736c90784a8b5608c3693e/charts/gazette/templates/deployment.yaml#L50)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Hmm, this was driven by encountering a startup error on the examples. I assumed it was due to an intended removal of the flag and made this change mechanically. Though, looks like the flag changed from `etcdEndpoint` to `etcd` (we should confirm the internal project isn't affected).
</blockquote></details>

Ah right. I forgot that the previous envflag appended `-Endpoint`. The internal project now has its own variant of the factory function, so it's not affected.

---

*[pkg/recoverylog/playback.go, line 377 at r5](https://reviewable.io:443/reviews/liveramp/gazette/39#-L4H5FtITBPJpuSae329:-L4H5FtITBPJpuSae32A:b48zdf7) ([raw file](https://github.com/liveramp/gazette/blob/19c78053207890ed0be7c6429453b9afd279ee49/pkg/recoverylog/playback.go#L377)):*
> ```Go
> 			// ErrDesyncDetected is returned by FixedFraming.Unmarshal (and not Unpack, meaning the reader
> 			// is still in a good state). This frame is garbage, but playback can continue.
> 			log.WithField("mark", fsm.LogMark).Warn("detected de-synchronization")
> ```

I think this should clear `err` to avoid potentially being caught by the error checking in the `defer`.

_** Leaving this comment here, although it might be rendered obsolete by a later commit in this PR. **_

---

*[pkg/recoverylog/playback_test.go, line 383 at r5](https://reviewable.io:443/reviews/liveramp/gazette/39#-L4HN6yQabVJDQ4JzZyd:-L4HN6yQabVJDQ4JzZye:b-dfjg1g) ([raw file](https://github.com/liveramp/gazette/blob/19c78053207890ed0be7c6429453b9afd279ee49/pkg/recoverylog/playback_test.go#L383)):*
> ```Go
> 	// Expect decoded operation includes first & last offset of the exact operation frame.
> 	var b = frameRecordedOp(newCreateOp("/a/path"), nil)
> 	var br = bufio.NewReader(bytes.NewReader(append(b, "extra"...)))
> ```

What is the purpose of appending "extra" to the framed op?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/39#-:-L4HPnSrZSZuvQ7LgYEA:b138m8p)*

**Comment by rupertchen** [comment]
:lgtm: % nits.

---

Reviewed 7 of 7 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/recoverylog/playback.go, line 377 at r5](https://reviewable.io:443/reviews/liveramp/gazette/39#-L4H5FtITBPJpuSae329:-L4ImA2dhV3xY3Rp6fmZ:b-vlh52z) ([raw file](https://github.com/liveramp/gazette/blob/19c78053207890ed0be7c6429453b9afd279ee49/pkg/recoverylog/playback.go#L377)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

I think this should clear `err` to avoid potentially being caught by the error checking in the `defer`.

_** Leaving this comment here, although it might be rendered obsolete by a later commit in this PR. **_
</blockquote></details>

Comment is obsolete.

---

*[pkg/recoverylog/playback.go, line 101 at r7](https://reviewable.io:443/reviews/liveramp/gazette/39#-L4Il3U_SOU_RhuQ6Pb9:-L4Il3Ua2oexEnIBtJh_:bvudjzt) ([raw file](https://github.com/liveramp/gazette/blob/7f16ebdfd6d0de3111517e2c8cb77be85b240bee/pkg/recoverylog/playback.go#L101)):*
> ```Go
> // Play using the prepared Player. Returns on the first encountered
> // unrecoverable error, or upon a successful MakeLive or Handoff.
> // Deprecated: Remove after context is plumbed through (Issue #37).
> ```

Nit: [Godoc convention](https://blog.golang.org/godoc-documenting-go-code) is to start a new paragraph ("blank" line). 

Example: https://golang.org/src/syscall/syscall_windows.go?h=deprecated#L25

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/39#-:-L4MZLk9ormCUok1mZsH:b-thzf2u)*

**Comment by jgraettinger** [comment]
Thanks!

---

Review status: 3 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/recoverylog/playback.go, line 101 at r7](https://reviewable.io:443/reviews/liveramp/gazette/39#-L4Il3U_SOU_RhuQ6Pb9:-L4aorg6MWbtpm9nAMDE:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/7f16ebdfd6d0de3111517e2c8cb77be85b240bee/pkg/recoverylog/playback.go#L101)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: [Godoc convention](https://blog.golang.org/godoc-documenting-go-code) is to start a new paragraph ("blank" line). 

Example: https://golang.org/src/syscall/syscall_windows.go?h=deprecated#L25
</blockquote></details>

Done.

---

*[pkg/recoverylog/playback_test.go, line 383 at r5](https://reviewable.io:443/reviews/liveramp/gazette/39#-L4HN6yQabVJDQ4JzZyd:-L4apO_RqY0dMy8V-Itx:b-56xt6b) ([raw file](https://github.com/liveramp/gazette/blob/19c78053207890ed0be7c6429453b9afd279ee49/pkg/recoverylog/playback_test.go#L383)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

What is the purpose of appending "extra" to the framed op?
</blockquote></details>

It's there to sanity-check that the exact encoded operation length is read (rather than reading to end-of-buffer). Removed already in later commit.

---

*[pkg/recoverylog/recorded_op.proto, line 23 at r1](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42TlOQ_OauWR2wZnnZ:-L4aqB86JDc7dMOKO3ok:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/2f7d5b39663ab46c6d1745d814376d01d976957b/pkg/recoverylog/recorded_op.proto#L23)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: write => wrote
</blockquote></details>

Done.

---

*[test/NOTES.rst, line 4 at r4](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42pl1OTtlez3kjc3q3:-L4aqY5DBgvZrW30jUcV:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/5f39cab876301ababbacd2352b4cf3fc4a0bc030/test/NOTES.rst#L4)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

RST syntax: [embeded link](http://docutils.sourceforge.net/docs/user/rst/quickref.html#external-hyperlink-targets):

```rst
Bootstrap an Etcd cluster using `Etcd operator <https://coreos.com/blog/introducing-the-etcd-operator.html>`_.
```


</blockquote></details>

Done.

---

*[test/NOTES.rst, line 13 at r4](https://reviewable.io:443/reviews/liveramp/gazette/39#-L42riOOK57qrg3IuSDK:-L4aqtk05Ry4O5ajhDsP:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/5f39cab876301ababbacd2352b4cf3fc4a0bc030/test/NOTES.rst#L13)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

RST syntax: [inline literal](http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup), use double backquotes.

```rst
This will setup the ``examples`` bucket.
```

There's several instances of this in this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/39#-:-L4asFXIF61qIMNQGc8K:b-ucfknh)*

**Pull request merged**
