### PR TITLE
Add debug/profiler controls via signals

### PR DESCRIPTION
**Pull request by rupertchen**
Jira: PUB-4389

### CODE REVIEW

**Comment by rupertchen** [comment]
@jgraettinger, Could you also take a look?

**Comment by jgraettinger** [comment]
What about collapsing `pprof` and `mainboilerplate` into a single package? The signaling stuff is not really `pprof` per-se, since that has a very specific meaning from the std library, and the packages are conceptually related (both are providing functionality for operationalization-related concerns). Straw man: `ops` ? `opsutil` ?

**Comment by rupertchen** [comment]
Collapsing `pprof` into `mainboilerplate` makes sense. I had started the package by mimicking `net/http/pprof`, but this is a far simpler package.

**Comment by rupertchen** [comment]
@jgraettinger , @joshk0: PTAL.

**Comment by joshk0** [comment]
Haha oh shit, my email filters are not set up for this anymore! I totally missed _all_ of this.

**Comment by joshk0** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/1#-:-KxraNmJGqYhYHUQP3Dh:bnfp4nl)*

**Pull request merged**
