### PR TITLE
Draft/pub 3743 enable compression s3 uploads

### PR DESCRIPTION
**Pull request by brennanrieger**
This change is [Reviewable](https://reviewable.io/reviews/liveramp/gazette/10)

### CODE REVIEW

**Comment by brennanrieger** [comment]
Ready for a first pass @tylercunnion.

**Comment by tylercunnion** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cloudstore/s3_file.go, line 78 at r1](https://reviewable.io:443/reviews/liveramp/gazette/10#-L-Z0M-ZG6fIoDTeL4r0:-L-Z0M-ZG6fIoDTeL4r1:bm9geid) ([raw file](https://github.com/liveramp/gazette/blob/9361558427213a2af338be2cda6a9bd39f537024/cloudstore/s3_file.go#L78)):*
> ```Go
> func (f *s3File) Write(p []byte) (int, error) {
> 	var buf = &f.spool
> 	var compressor = gzip.NewWriter(buf)
> ```

I feel like the compressor should be created during OpenFile as a property of the s3File, rather than making a new one on every Write operation.

---

*[cloudstore/s3_file.go, line 83 at r1](https://reviewable.io:443/reviews/liveramp/gazette/10#-L-Z0LJk0C8y-MPnO_a9:-L-Z0LJk0C8y-MPnO_aA:b-mkncps) ([raw file](https://github.com/liveramp/gazette/blob/9361558427213a2af338be2cda6a9bd39f537024/cloudstore/s3_file.go#L83)):*
> ```Go
> 
> 	// Write to in-memory spool.
> 	n, err := compressor.Write(p)
> ```

Looks like this is just going to use the compressor for every write, regardless of the flag, correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/10)*

**Comment by jgraettinger** [comment]
@brennanrieger please run `filesystem_tests` in this package against actual S3 before next review.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cloudstore/s3_file.go, line 78 at r1](https://reviewable.io:443/reviews/liveramp/gazette/10#-L-Z0M-ZG6fIoDTeL4r0:-L-wfZHlJqUmZUzLbaex:bi3z8iu) ([raw file](https://github.com/liveramp/gazette/blob/9361558427213a2af338be2cda6a9bd39f537024/cloudstore/s3_file.go#L78)):*
<details><summary><i>Previously, tylercunnion (Tyler Cunnion) wrote…</i></summary><blockquote>

I feel like the compressor should be created during OpenFile as a property of the s3File, rather than making a new one on every Write operation.
</blockquote></details>

Yea, this will create an unintelligible file -- one (and only one) gzip compression context must be used for the whole file.

Please compare with `gcs_fs.go`. I think you want to extensively lift that behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/10#-:-L-wgNW6wjNgmcZsA2Yd:bdy4bgn)*

**Comment by brennanrieger** [comment]
@tylercunnion I pushed some new commits here (they're hard to see because of rebasing) but it is working for me when I run filesystem_tests. Ready for a second pass

**Comment by brennanrieger** [comment]
Bump @tylercunnion

**Comment by tylercunnion** [comment]
Gah first of all sorry I let this lapse for so long - danger of multiple repositories I guess

But yeah, filesystem tests look good; doesn't look like this should have any external side effects so :lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/10#-:-L3TfVY39_NS4CSL8ufq:bjqlfid)*

**Pull request merged**
