### PR TITLE
recoverylog: make playback hand-off fast & deterministic

### PR DESCRIPTION
**Pull request by jgraettinger**
Formerly, `recoverylog` playback used behavior of waiting for a timeout
during which no new content became available from the broker. On
reaching that timeout, playback was assumed to be complete and the
consumer would switch from replicating to recording new state changes.

This invited race conditions, where a prior recorder which was delayed
in flushing final writes to the log would race with the new recorder.
Ordinarily FSMHints are sufficient to resolve the forked log history,
but this is a problem for other warm-standby replicas which are
live-tailing the log: depending on which raced write wins, they may
follow a fork of log history which is shutting down, and ignored the new
recorder entirely.

Fix this by changing player behavior to allow for injecting "hand-off"
noop RecordedOps, which serve as write-barriers that effectively give
control of the log to a new recorder in the eyes of any other tailers of
the log. Timeout-based polling is removed entirely.

This has a number of spill-over implications. Playback must now use a
mix of blocking and non-blocking reads, and `RetryReader` is refactored
to support this behavior. Use of Context is introduced to signal
deadlines and cancellations, and the server-side blocking duration
mechanic is deprecated (in favor of client-side cancellation). The
Author ID must be shared between the `Player` and `Recorder`, motivating
a refactor of `consumer/master.go`.

Also, switch ShardPreInitHook => ShardPostInitHook. In usages such as
ShardIndex, the expectation is the Shard is fully initialized, making a
Post-hook appropriate.

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/gazette/4)

### CODE REVIEW

**Comment by rupertchen** [comment]
Publishing partial review feedback.

`routines.go` has a bug, other items are nits.

---

Reviewed 17 of 23 files at r1.
Review status: 17 of 23 files reviewed at latest revision, 7 unresolved discussions.

---

*[consumer/routines.go, line 117 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky21V0dIwG8XcU2M7Zq:-Ky21V0dIwG8XcU2M7Zr:b-usky2e) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L117)):*
> ```Go
> func hintsJSONString(hints recoverylog.FSMHints) string {
> 	if b, err := json.Marshal(hints); err != nil {
> 		panic(err.Error()) // JSON serialization of FSMHints can never fail.
> ```

Nit: I prefer "... must never fail."; with "can", the statement could be interpreted as an claim that it is impossible.

Honestly, this may just be me reading too many RFCs recently.

---

*[consumer/routines.go, line 130 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky24iP80USZuMpwp7q4:-Ky24iP80USZuMpwp7q5:b-xcoum6) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L130)):*
> ```Go
> 	// Etcd Set is best-effort.
> 	if err != nil {
> 		log.WithFields(log.Fields{"path": hintsPath, "err": err}).
> ```

`hintsPath` => `key`. This compiles because there is a `hintsPath` func.

---

*[consumer/routines.go, line 131 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky24KNf61xE8D77sUve:-Ky24KNf61xE8D77sUvf:b-qdq4vu) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L131)):*
> ```Go
> 	if err != nil {
> 		log.WithFields(log.Fields{"path": hintsPath, "err": err}).
> 			Warn("failed to store hints")
> ```

Change warning message now that this could be a set for other reasons.

---

*[consumer/routines.go, line 167 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky23b_qlcJYdl-AZi98:-Ky23b_qlcJYdl-AZi99:b-hudt16) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L167)):*
> ```Go
> }
> 
> // Deprecated. Stores legacy |offsets| in Etcd.
> ```

Nit: Proposed convention for [documenting](https://blog.golang.org/godoc-documenting-go-code) deprecations is to add a paragraph beginning with "Deprecated:".

Example: https://github.com/golang/go/blob/master/src/net/http/transport.go#L107

---

*[journal/protocol.go, line 75 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky2EUb3Ds4nJvH_VMtF:-Ky2EUb3Ds4nJvH_VMtG:bwjfiyy) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/protocol.go#L75)):*
> ```Go
> 	// not available (eg, because it represents a portion of Journal which has
> 	// been permantently deleted), the broker will return the next available
> 	// offset. Callers should therefor always inspect the ReadResult Offset.
> ```

Typo: therefor(e)"

---

*[journal/protocol.go, line 85 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky2KPrmEmK0f09Zjtv3:-Ky2KPrmEmK0f09Zjtv4:b-78xqrf) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/protocol.go#L85)):*
> ```Go
> 	// The time at which blocking will expire
> 	// DEPRECATED. Server-side support for deadlines will be removed. Use
> 	// context.WithDeadline instead.
> ```

See previous comment about godoc convention for deprecation.

---

*[recoverylog/recorder.go, line 210 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky2aFGMoK3u7uLr1uEs:-Ky2aFGMoK3u7uLr1uEt:btkl464) ([raw file](https://github.com/liveramp/gazette/blob/86dfb0d3299e4178aac6e3343180d31601df440b/recoverylog/recorder.go#L210)):*
> ```Go
> 
> func (r *Recorder) process(op RecordedOp, b []byte) []byte {
> 	if r.fsm.NextSeqNo == 0 {
> ```

Is this zero-check being removed because a op with `SeqNo=0` is expected to be rejected as mis-sequenced?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/4#-:-Ky2wMRN38Yu7e5ttth5:b-1lfxwc)*

**Comment by rupertchen** [comment]
Reviewed 1 of 23 files at r1.
Review status: 18 of 23 files reviewed at latest revision, 8 unresolved discussions.

---

*[journal/memory_broker.go, line 75 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky36wYWeMntdo2bKq9O:-Ky36wYXOylVUsUwrbb5:b-cyl9mk) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/memory_broker.go#L75)):*
> ```Go
> 	}
> 
> 	for i := 0; true; i++ {
> ```

`i` isn't used elsewhere, could this be `for { ... }`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/4)*

**Comment by rupertchen** [comment]
Finished first pass.

---

Reviewed 5 of 23 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[journal/io.go, line 73 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyHHNSCFDZo6vjdou_l:-KyHHNSCFDZo6vjdou_m:bctz4y6) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/io.go#L73)):*
> ```Go
> 
> // NewRetryReader returns a RetryReader at |mark|, and using the provided
> // |getter| and |ctx| for all operations.
> ```

Nit 1: This is the only new documentation I've seen (so far) that uses the `|foo|` notation. Is that intentional?
Nit 2: `ctx` is not an argument. Should it be, or will it be very soon?

---

*[recoverylog/playback.go, line 34 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyHuFirDhUxjushuVcA:-KyHuFirDhUxjushuVcB:bp34uvd) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L34)):*
> ```Go
> 
> // NewPlayer returns a new Player for recovering the log indicated by |hints|
> // into |dir|. An error is returned if |hints| are invalid.
> ```

Mismatch between arg name and doc: `dir` vs `localDir`.

---

*[recoverylog/playback.go, line 61 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyHxzLivBp-zTPG9wRJ:-KyHxzLjWZnj4jAxekpY:b-qmnmym) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L61)):*
> ```Go
> // InjectHandoff may be made of a Player instance.
> func (p *Player) FinishAtWriteHead() *FSM {
> 	p.handoffCh <- 0
> ```

Is it worth it to panic if more than one invocation is made?

---

*[recoverylog/playback.go, line 100 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIDA99DypQ03InLSnK:-KyIDA99DypQ03InLSnL:b2rhl72) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L100)):*
> ```Go
> func (p *Player) Play(client journal.Client) error {
> 	// Start an adapter to close the playLog Context on cancelCh being selectable.
> 	// TODO(johnny): Remove after context is plumbed through Play.
> ```

Q: Isn't the TODO unnecessary if `Player.Play` is deprecated? I assume this whole method will be deleted and `Player.PlayContext` will be called directly.

---

*[recoverylog/playback.go, line 214 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIAldEa4WcEFMKZBFV:-KyIAldEa4WcEFMKZBFW:b-p40gud) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L214)):*
> ```Go
> 	playerStateBackfill playerState = iota
> 	// Player is tailing new log content as it is written.
> 	playerStateTailing playerState = iota
> ```

Opinion:
1) `playLog` treats `playerStateTailing` identically to `playerStateBackfill` in all cases. Should they be merged to a `playerStateReading`?
2) Rename `playerStateBackfill` to `playerStateBackfilling` to be consistent with `playerStateTailing`.

---

*[recoverylog/playback.go, line 216 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIB6qzHZZbJkatnro_:-KyIB6qzHZZbJkatnroa:bqtg252) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L216)):*
> ```Go
> 	playerStateTailing playerState = iota
> 	// Player will exit after reading through the current log head.
> 	playerStateExitingAtHead playerState = iota
> ```

Opinion: Rename to `playerStateExitAtHead` to be consistent in tense with `playerStateHandoff*`?

---

*[recoverylog/playback_test.go, line 512 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIUwR9AyS-Gad-8XiW:-KyIUwRAU9eB1jxmXJsP:blf4x86) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback_test.go#L512)):*
> ```Go
> func newPlayOperationHelper(c *gc.C) playOperationHelper {
> 	var err error
> 	var tpc = playOperationHelper{
> ```

Q: What does `tpc` mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/4#-:-KyIWesXWwMqh_GGA42m:b-xhgvng)*

**Comment by jgraettinger** [comment]
Thanks! PTAL

FYI I've tested using the `build` branch I'll be putting up for review next.

---

Review status: 15 of 25 files reviewed at latest revision, 15 unresolved discussions.

---

*[consumer/routines.go, line 117 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky21V0dIwG8XcU2M7Zq:-Ky3Jt1Bq8j90T5HS0qe:b8cii47) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L117)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: I prefer "... must never fail."; with "can", the statement could be interpreted as an claim that it is impossible.

Honestly, this may just be me reading too many RFCs recently.
</blockquote></details>

I actually meant that it is impossible. If you dig into the generated protobuf Marshal (or the stdlib JSON Marshal for that matter), the error return is part of the signature only to allow for embedded user-defined encoding functions which are permitted to return error (and which RecordedOp doesn't use). The generated code never errors, therefor it can never fail.

---

*[consumer/routines.go, line 130 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky24iP80USZuMpwp7q4:-KyI29oOJg9o2waKrpHN:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L130)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

`hintsPath` => `key`. This compiles because there is a `hintsPath` func.
</blockquote></details>

Done.

---

*[consumer/routines.go, line 131 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky24KNf61xE8D77sUve:-KyI2IEJUvtIUzKaSpG4:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L131)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Change warning message now that this could be a set for other reasons.
</blockquote></details>

Done.

---

*[consumer/routines.go, line 167 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky23b_qlcJYdl-AZi98:-KyI2idGVOmuUi7LxyY7:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/consumer/routines.go#L167)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: Proposed convention for [documenting](https://blog.golang.org/godoc-documenting-go-code) deprecations is to add a paragraph beginning with "Deprecated:".

Example: https://github.com/golang/go/blob/master/src/net/http/transport.go#L107
</blockquote></details>

Done.

---

*[journal/io.go, line 73 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyHHNSCFDZo6vjdou_l:-KyJPCWnKWd1IPQoQhJ1:b-r93kgi) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/io.go#L73)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit 1: This is the only new documentation I've seen (so far) that uses the `|foo|` notation. Is that intentional?
Nit 2: `ctx` is not an argument. Should it be, or will it be very soon?
</blockquote></details>

1) No, not intentional. I don't have a lot of conviction either way whether we should be using these for godoc comments (perhaps a mild preference to keep it). I do think it adds clarity within function comments.

2) Added NewRetryReaderContext. I'm not finding the particular golang.org post at the moment, but IIRC the recommended migration pattern is to add `FooContext` methods, switch call sites to use those, and eventually rename back to `Foo` when all usages are updated. 

---

*[journal/memory_broker.go, line 75 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky36wYWeMntdo2bKq9O:-Ky3Kx9jIc2DUjvrtP-B:b-1io605) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/memory_broker.go#L75)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

`i` isn't used elsewhere, could this be `for { ... }`?
</blockquote></details>

Huh, would have thought the compiler would catch that. Done.

---

*[journal/protocol.go, line 75 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky2EUb3Ds4nJvH_VMtF:-KyI3-CR9tosgqq5wrnB:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/protocol.go#L75)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Typo: therefor(e)"
</blockquote></details>

Done.

---

*[journal/protocol.go, line 85 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky2KPrmEmK0f09Zjtv3:-KyI32lxHUEdOZTbvzu_:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/journal/protocol.go#L85)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

See previous comment about godoc convention for deprecation.
</blockquote></details>

Done.

---

*[recoverylog/playback.go, line 34 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyHuFirDhUxjushuVcA:-KyJQCb3pTb_Cx3fUjIZ:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L34)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Mismatch between arg name and doc: `dir` vs `localDir`.
</blockquote></details>

Done.

---

*[recoverylog/playback.go, line 61 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyHxzLivBp-zTPG9wRJ:-KyJQslRbID0L8jev2oY:b-scz294) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L61)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Is it worth it to panic if more than one invocation is made?
</blockquote></details>

added a `close`, which will cause a future send to panic.

---

*[recoverylog/playback.go, line 100 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIDA99DypQ03InLSnK:-KyJRDkym7_L5S_ayC2s:b-a0nmm1) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L100)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Q: Isn't the TODO unnecessary if `Player.Play` is deprecated? I assume this whole method will be deleted and `Player.PlayContext` will be called directly.
</blockquote></details>

Yes. I just want to clarify again that this is intended as temporary.

---

*[recoverylog/playback.go, line 214 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIAldEa4WcEFMKZBFV:-KyJRR1OFXPETW7DYVFb:b-qbsdsd) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L214)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Opinion:
1) `playLog` treats `playerStateTailing` identically to `playerStateBackfill` in all cases. Should they be merged to a `playerStateReading`?
2) Rename `playerStateBackfill` to `playerStateBackfilling` to be consistent with `playerStateTailing`.
</blockquote></details>

1) the distinction of the two states is used to make sure we `close(tailingCh)` exactly once, at transition from backfill to tailing, ~L280. Otherwise we'd need another bit somewhere else.

2) Done, in the opposite way.

---

*[recoverylog/playback.go, line 216 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIB6qzHZZbJkatnro_:-KyJSkmu_iy11WOPQlVZ:b46cjz1) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback.go#L216)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Opinion: Rename to `playerStateExitAtHead` to be consistent in tense with `playerStateHandoff*`?
</blockquote></details>

Reworked all of these.

---

*[recoverylog/playback_test.go, line 512 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-KyIUwR9AyS-Gad-8XiW:-KyJT8Z6T2hSooOIfX8b:b-sdd7d7) ([raw file](https://github.com/liveramp/gazette/blob/6ca580e98e9bf9c55fa654a73c4b04e53e50969d/recoverylog/playback_test.go#L512)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Q: What does `tpc` mean?
</blockquote></details>

`testPlaybackContext`, which this type was originally called. switched to `poh`.

---

*[recoverylog/recorder.go, line 210 at r1](https://reviewable.io:443/reviews/liveramp/gazette/4#-Ky2aFGMoK3u7uLr1uEs:-KyI3KoSIZwDkRUgToPN:b-9xebbv) ([raw file](https://github.com/liveramp/gazette/blob/86dfb0d3299e4178aac6e3343180d31601df440b/recoverylog/recorder.go#L210)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Is this zero-check being removed because a op with `SeqNo=0` is expected to be rejected as mis-sequenced?
</blockquote></details>

This is a hold-over from a very early implementation detail (long since removed) where an FSM with NextSeqNo == 0 was allowed to match any SeqNo.

There's no longer any special handling for zero, and in any case `NewFSM` initializes NextSeqNo to 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/4#-:-KyJTtEz1CT1GjdWlUh5:buscz1q)*

**Comment by rupertchen** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/4#-:-KyM7xZpheLyip1RT5ay:bnfp4nl)*

**Pull request merged**
