### PR TITLE
Gazette build system & example application; revert ignored routes

### PR DESCRIPTION
**Pull request by jgraettinger**
Re: ignored routes, see PUB-4117.

This PR otherwise introduces a Docker-ized build system for Gazette, a word-count toy example, and initial Helm charts for standing up Gazette clusters.

`build/README.rst` provides instructions on building containers, and `test/NOTES.rst` is my current state of notes on bringing up a cluster with the word-count example for testing.

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/gazette/6)

### CODE REVIEW

**Comment by rupertchen** [comment]
Publishing a partial review of first two commits.

---

Reviewed 6 of 6 files at r1, 14 of 14 files at r2.
Review status: 20 of 38 files reviewed at latest revision, 11 unresolved discussions.

---

*[build/Dockerfile.gazette-base, line 4 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRhCXdReHIGj4bZjwd:-KyRhCXdReHIGj4bZjwe:biopjei) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-base#L4)):*
> ```
> 
> ENV ROCKSDB_VERSION 5.3.5
> ENV PROTO_VERSION 3.4.0
> ```

Opinion: Consider moving `ENV` commands below the `RUN apt-get`.

Docker's docs prefer setting multiple variables in a single line since it will produce a single layer for caching. My own (weak) preference is to move each closer to it's first usage so after an update, fewer cache layers are invalidated.

Q: Do we care about having these env vars in the final container? If not, should we inline them so they don't appear there?

---

*[build/Dockerfile.gazette-base, line 18 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRfEompyOUApTII1FH:-KyRfEompyOUApTII1FI:b-bpbhpp) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-base#L18)):*
> ```
>       libzstd-dev \
>       unzip \
>       zlib1g-dev \
> ```

Q: Where does this list come from? It has some entries that use different versions from what we have used elsewhere (e.g., `libgflags-dev` vs `libgflags2`).

---

*[build/Dockerfile.gazette-build, line 59 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRmlCU_TE1I_RuaTLU:-KyRmlCU_TE1I_RuaTLV:bydjppv) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-build#L59)):*
> ```
>     ; do \
>       mockery -inpkg -name $(basename ${tgt}) -dir /go/src/$(dirname ${tgt}) ; \
>     done ;
> ```

Thought: I have been thinking about trying a branch where mocks are placed in a `mock` package "under" the interface's import path and using `go:generate` directives. That would simplify the command here and keep mocks out of "production" packages.

The caveat is I think this is a worthwhile trade only if we can get away with default `mockery` options to keep directives minimal. E.g., `go:generate mockery -name MyInterface`.

---

*[build/Dockerfile.gazette-build, line 69 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRqHGbmdx54bZ1-iiM:-KyRqHGbmdx54bZ1-iiN:b725ar3) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-build#L69)):*
> ```
> # TODO(johnny): Use a recursive go install gazette/pkg/...
> RUN go install github.com/LiveRamp/gazette/cmd/gazette
> RUN go install github.com/LiveRamp/gazette/cmd/run-consumer
> ```

Why not use `go install github.com/LiveRamp/gazette/cmd/...` even before we have `gazette/pkg`?

---

*[build/Dockerfile.gazette-build, line 73 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRqd0OSMhYId22ulCS:-KyRqd0OSMhYId22ulCT:b-j8s90v) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-build#L73)):*
> ```
> # Test all packages.
> # TODO(johnny): Use a recursive go test gazette/pkg/...
> RUN go test github.com/LiveRamp/gazette/async
> ```

Why not use `go test github.com/LiveRamp/gazette/...` even before we have `gazette/pkg`?

---

*[build/README.rst, line 11 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyN8YH-WSviteSnE_ui:-KyN8YH-WSviteSnE_uj:b-e83pgp) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/README.rst#L11)):*
> ```reStructuredText
> but still require the RocksDB runtime:
> 
>   ``docker build . -f build/Dockerfile.gazette-base --tag gazette-base``
> ```

FYI, this is how to do code blocks and literal blocks in rST: https://gist.github.com/rupertchen/9b6ca6f1c4fe42eeb05e759d32a31c72.

I've included a short-hand version of `::` where it is placed at the end of a paragraph and renders as a single `:` as you may see it around. I tend to avoid it as thinking about an extra form and saving a couple new lines isn't worth it IMO.

---

*[cmd/run-consumer/main.go, line 91 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KySshGlqVFxcCsC55lg:-KySshGlqVFxcCsC55lh:b-266s4v) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/cmd/run-consumer/main.go#L91)):*
> ```Go
> 		LocalDir:        *dir,
> 		ConsumerRoot:    *root,
> 		RecoveryLogRoot: filepath.Join(*root, "recovery-logs")[1:], // TODO(johnny): Fix me.
> ```

What needs to be fixed here?

---

*[consensus/route.go, line 23 at r1](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyN4XHffAI36tnNg1Dj:-KyN4XHffAI36tnNg1Dk:b-a8dnfh) ([raw file](https://github.com/liveramp/gazette/blob/7b94155c60e496c7fee5bdeafb87367abd924d44/consensus/route.go#L23)):*
> ```Go
> // NewRoute initializes a new Route from the |response| and |node|.
> func NewRoute(response *etcd.Response, node *etcd.Node) Route {
> 	rt := Route{
> ```

Should we keep the replacement of the short assignements? Perhaps we should add something about code styles to the project doc soon.

---

*[examples/word-count/topics.go, line 57 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyStbwWz2_i-W0C44oN:-KyStbwWz2_i-W0C44oO:b463zkz) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/topics.go#L57)):*
> ```Go
> 
> // Encode implements topic.Framing.
> func (*sentenceFraming) Encode(msg topic.Message, b []byte) ([]byte, error) {
> ```

Nit: Value as receiver since `sentenceFraming` holds no state.

`Sentences.Framing = new(sentenceFraming)` would still work thought I'd be inclined to swap it to `sentenceFraming{}`.

---

*[examples/word-count/counter/counter.go, line 15 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KySvp0gOApQOkjnhJaZ:-KySvp0gOApQOkjnhJa_:b-dgoi2j) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/counter/counter.go#L15)):*
> ```Go
> type counter struct{}
> 
> func (c *counter) Topics() []*topic.Description {
> ```

Same opinion as for `sentenceFraming` and `shuffler`.

---

*[examples/word-count/shuffler/shuffler.go, line 16 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KySuzVvqARTz9aUZGd4:-KySuzVvqARTz9aUZGd5:b-go5fw0) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/shuffler/shuffler.go#L16)):*
> ```Go
> type shuffler struct{}
> 
> func (c *shuffler) Topics() []*topic.Description {
> ```

Same opinion as for `sentenceFraming`. Additionally could drop `c`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/6#-:-KySwibUZYwVUvDtXo0v:brx2ot)*

**Comment by jgraettinger** [comment]
Thanks, PTAL!

---

Review status: 12 of 38 files reviewed at latest revision, 11 unresolved discussions.

---

*[build/Dockerfile.gazette-base, line 4 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRhCXdReHIGj4bZjwd:-KyWHZsWfpZR7YITNKi4:bz9f67x) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-base#L4)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Opinion: Consider moving `ENV` commands below the `RUN apt-get`.

Docker's docs prefer setting multiple variables in a single line since it will produce a single layer for caching. My own (weak) preference is to move each closer to it's first usage so after an update, fewer cache layers are invalidated.

Q: Do we care about having these env vars in the final container? If not, should we inline them so they don't appear there?
</blockquote></details>

Switched these to a single line. Leaving where they are, however: if we're ticking versions of these packages (a very infrequent change), I think we also want to be verifying compatibility with current debian packages. Otherwise there's a minor risk of weird caching affects / "works on my machine".

A: I think they should be available for inspection by downstream containers. Eg, Rocks is very actively developed and functionality / features changes with each release. I can definitely see wanting to be able to sanity check the version I'm running against.

---

*[build/Dockerfile.gazette-base, line 18 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRfEompyOUApTII1FH:-KyWIDQH4pegzvKcNYqB:b-bwrddj) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-base#L18)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Q: Where does this list come from? It has some entries that use different versions from what we have used elsewhere (e.g., `libgflags-dev` vs `libgflags2`).
</blockquote></details>

since we're building rocks from source (rather than a pre-build deb package), we need the `-dev` versions of `gflags`. I also did an audit to ensure we're including dev packages for all compression modes that RocksDB supports so they're available at runtime (in particular, `lz4` looks interesting).

In theory we could have a separate runtime container which had most of this, but swapped out `libgflags-dev` for `libgflags2`, but IMO that's not worth it (these packages are small, and compiling cgo bindings requires dev packages for most of them anyway).

---

*[build/Dockerfile.gazette-build, line 59 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRmlCU_TE1I_RuaTLU:-KyWJ_LT7Q5VkaDzmTpk:b8o9r2p) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-build#L59)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Thought: I have been thinking about trying a branch where mocks are placed in a `mock` package "under" the interface's import path and using `go:generate` directives. That would simplify the command here and keep mocks out of "production" packages.

The caveat is I think this is a worthwhile trade only if we can get away with default `mockery` options to keep directives minimal. E.g., `go:generate mockery -name MyInterface`.
</blockquote></details>

It won't work with un-exported mocks like `httpClient`. I'm not opposed in principle, but it'd take further refactoring to get there.

I'm not sure what practical value is bought by separating them into a different import path. I did go back and ensure `mock_` and `pb.go` are part of the `.dockerignore`, to ensure any local copies aren't shipped into the build context.

---

*[build/Dockerfile.gazette-build, line 69 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRqHGbmdx54bZ1-iiM:-KyWKxrG4zmPj3pZ9zRc:b-yoktwj) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-build#L69)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Why not use `go install github.com/LiveRamp/gazette/cmd/...` even before we have `gazette/pkg`?
</blockquote></details>

good call! done

---

*[build/Dockerfile.gazette-build, line 73 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyRqd0OSMhYId22ulCS:-KyWL7AC-do-5WP23VkQ:bkv832i) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/Dockerfile.gazette-build#L73)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Why not use `go test github.com/LiveRamp/gazette/...` even before we have `gazette/pkg`?
</blockquote></details>

annoyingly that will also test the entire `vendor` directory.

---

*[build/README.rst, line 11 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyN8YH-WSviteSnE_ui:-KyWNPRoJo2ieoBaAAmI:b9cb02b) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/build/README.rst#L11)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

FYI, this is how to do code blocks and literal blocks in rST: https://gist.github.com/rupertchen/9b6ca6f1c4fe42eeb05e759d32a31c72.

I've included a short-hand version of `::` where it is placed at the end of a paragraph and renders as a single `:` as you may see it around. I tend to avoid it as thinking about an extra form and saving a couple new lines isn't worth it IMO.


</blockquote></details>

thanks. updated.

---

*[cmd/run-consumer/main.go, line 91 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KySshGlqVFxcCsC55lg:-KyWOQQeKJpkZA-xonLr:b-4ehrge) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/cmd/run-consumer/main.go#L91)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

What needs to be fixed here?
</blockquote></details>

fixed. want `recover-logs` as a top-level parallel hierarchy, but that requires figuring out how to bootstrap multiple minio buckets on minikube.

---

*[consensus/route.go, line 23 at r1](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyN4XHffAI36tnNg1Dj:-KyWOZE5emg5xGikiVD5:byzbopr) ([raw file](https://github.com/liveramp/gazette/blob/7b94155c60e496c7fee5bdeafb87367abd924d44/consensus/route.go#L23)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Should we keep the replacement of the short assignements? Perhaps we should add something about code styles to the project doc soon.
</blockquote></details>

yes, just because I'd like to leave this as a pure git revert of that commit.

---

*[examples/word-count/topics.go, line 57 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyStbwWz2_i-W0C44oN:-KyWPIMoABwiS7wz-dWR:buv709u) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/topics.go#L57)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: Value as receiver since `sentenceFraming` holds no state.

`Sentences.Framing = new(sentenceFraming)` would still work thought I'd be inclined to swap it to `sentenceFraming{}`.
</blockquote></details>

it actually wouldn't still work, making it value recv requires `sentenceFraming{}`. Done

---

*[examples/word-count/counter/counter.go, line 15 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KySvp0gOApQOkjnhJaZ:-KyWPW0FYO9rkfMMXSGY:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/counter/counter.go#L15)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Same opinion as for `sentenceFraming` and `shuffler`.
</blockquote></details>

Done.

---

*[examples/word-count/shuffler/shuffler.go, line 16 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KySuzVvqARTz9aUZGd4:-KyWP_hchNxECTu4iBny:b-896fix) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/shuffler/shuffler.go#L16)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Same opinion as for `sentenceFraming`. Additionally could drop `c`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/6#-:-KyWrTDGA4eDeOOeHimP:bnsdipc)*

**Comment by rupertchen** [comment]
:lgtm:

---

Reviewed 17 of 18 files at r3, 8 of 8 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/word-count/topics.go, line 57 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyStbwWz2_i-W0C44oN:-KyXRnM01HJ8C_AOdy2M:b-88gq3n) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/topics.go#L57)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

it actually wouldn't still work, making it value recv requires `sentenceFraming{}`. Done
</blockquote></details>

Both forms work on the Go Playground: https://play.golang.org/p/f-vTw9GnWb

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/6#-:-KyXVq9B2Ua2zfJAByNe:bnfp4nl)*

**Comment by jgraettinger** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[examples/word-count/topics.go, line 57 at r2](https://reviewable.io:443/reviews/liveramp/gazette/6#-KyStbwWz2_i-W0C44oN:-KyXeB8sQM97YIip878w:bbgwohw) ([raw file](https://github.com/liveramp/gazette/blob/313cc487d27b6ac799b784f0613346bf7e63c8eb/examples/word-count/topics.go#L57)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Both forms work on the Go Playground: https://play.golang.org/p/f-vTw9GnWb
</blockquote></details>

_whaaa, what is this sorcery!?_

(you're right).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/6)*

**Pull request merged**
