### PR TITLE
INTL-549 Fetch S3 region dynamically

### PR DESCRIPTION
**Pull request by fgoncalveslr**
@joshk0 could you take a look at this one please? Please lmk if I should tag someone else (although you seem to have contributed quite a lot to this file).

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/gazette/11)

### CODE REVIEW

**Comment by jgraettinger** [comment]
This assumes your running within the target EC2 region, and will break usages which aren't (eg, transfers to S3 from GCP, or across regions, or from colo), no?

How about specifying this by environment variable? `AWS_DEFAULT_REGION` looks [canonical](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html).

See also: `filesystem_test.go` in this package can validate against actual S3.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/11#-:-L-YMg5TbfCQNi28rcC1:b-9uf8ba)*

**Comment by fgoncalveslr** [comment]
Great point, thanks for the review. I didn't suspect that such use cases existed but it is true that this change would prevent them for working. I'll make the update.

**Comment by fgoncalveslr** [comment]
made a PR to add the env variable to gazette's deployment: https://git.liveramp.net/arbortech/workspace/pull/820

**Comment by jgraettinger** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/11#-:-L-b20deeU0Z5jANWgDE:bnfp4nl)*

**Comment by joshk0** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/liveramp/gazette/11#-:-L-biAkOP1VTh4_6iaw5:b-jbsf8z)*

**Comment by fgoncalveslr** [comment]
I don't have permissions to merge btw :)

**Pull request merged**
